name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build
    - name: Lint
      run: ./gradlew check
    - name: Run Tests
      run: ./gradlew test
    - name: Deploy login
      uses: "actions/heroku@master"
      with:
        args: "container:login"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Deploy push
      uses: "actions/heroku@master"
      with:
        args: "container:push web"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Deploy release
      uses: "actions/heroku@master"
      with:
        args: "container:release web"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
